# Change these first
owner: EWIZZDEV # Your GitHub organization or username, where this repository lives
repo: ewizz_status # The name of this repository

sites:
  - name: EWIZZ public page
    url: https://www.ewizz.co.za
  - name: EWIZZ customer portal
    url: https://office.ewizz.co.za
  - name: EWIZZ API
    url: https://api.ewizz.co.za/v2/user_code?ezcode=abcdef

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ewizz.ninja
  # baseUrl: /your-repo-name
  logoUrl: https://www.ewizz.co.za/wp-content/uploads/2013/12/ewizz-logo-web-white-601.png
  name: Systems status
  theme: dark
  introTitle:
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

robotsText: "User-agent: * \n Disallow: /"
commitMessages:
  commitAuthorName: "EWIZZ Status Bot"
  commitAuthorEmail: "bot@ewizz.co.za"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
